$secrets = @(
    "SESSION_SECRET=SESSION_SECRET:latest",
    "JWT_SECRET=JWT_SECRET:latest",
    "PGDATABASE=PGDATABASE:latest",
    "PGHOST=PGHOST:latest",
    "PGPORT=PGPORT:latest",
    "PGUSER=PGUSER:latest",
    "PGPASSWORD=PGPASSWORD:latest",
    "DATABASE_URL=DATABASE_URL:latest",
    "AI_INTEGRATIONS_OPENAI_API_KEY=AI_INTEGRATIONS_OPENAI_API_KEY:latest",
    "OPENAI_API_KEY=OPENAI_API_KEY:latest",
    "OPENAI_WEBHOOK_SECRET=OPENAI_WEBHOOK_SECRET:latest",
    "AI_INTEGRATIONS_GEMINI_API_KEY=AI_INTEGRATIONS_GEMINI_API_KEY:latest",
    "GEMINI_API_KEY=GEMINI_API_KEY:latest",
    "AI_INTEGRATIONS_ANTHROPIC_API_KEY=AI_INTEGRATIONS_ANTHROPIC_API_KEY:latest",
    "DEEPSEEK_API_KEY=DEEPSEEK_API_KEY:latest",
    "TELNYX_API_KEY=TELNYX_API_KEY:latest",
    "TELNYX_CONNECTION_ID=TELNYX_CONNECTION_ID:latest",
    "TELNYX_FROM_NUMBER=TELNYX_FROM_NUMBER:latest",
    "TELNYX_CALL_CONTROL_APP_ID=TELNYX_CALL_CONTROL_APP_ID:latest",
    "TELNYX_TEXML_APP_ID=TELNYX_TEXML_APP_ID:latest",
    "BASE_URL=BASE_URL:latest",
    "TELNYX_WEBHOOK_URL=TELNYX_WEBHOOK_URL:latest",
    "PUBLIC_WEBSOCKET_URL=PUBLIC_WEBSOCKET_URL:latest",
    "PUBLIC_WEBHOOK_HOST=PUBLIC_WEBHOOK_HOST:latest",
    "BRAVE_SEARCH_API_KEY=BRAVE_SEARCH_API_KEY:latest",
    "GOOGLE_SEARCH_API_KEY=GOOGLE_SEARCH_API_KEY:latest",
    "GOOGLE_SEARCH_ENGINE_ID=GOOGLE_SEARCH_ENGINE_ID:latest",
    "PSE_GOOGLE=PSE_GOOGLE:latest",
    "EMAIL_LIST_VERIFY_API_KEY=EMAIL_LIST_VERIFY_API_KEY:latest",
    "COMPANIES_HOUSE_API_KEY=COMPANIES_HOUSE_API_KEY:latest",
    "GOOGLE_AUTH_CLIENT_ID=GOOGLE_AUTH_CLIENT_ID:latest",
    "GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest",
    "MICROSOFT_CLIENT_ID=MICROSOFT_CLIENT_ID:latest",
    "MICROSOFT_CLIENT_SECRET=MICROSOFT_CLIENT_SECRET:latest",
    "MICROSOFT_TENANT_ID=MICROSOFT_TENANT_ID:latest",
    "MAILGUN_API_KEY=MAILGUN_API_KEY:latest",
    "MAILGUN_DOMAIN=MAILGUN_DOMAIN:latest",
    "REDIS_URL=REDIS_URL:latest",
    "GCS_BUCKET=GCS_BUCKET:latest",
    "S3_REGION=S3_REGION:latest",
    "VOICE_PROVIDER=VOICE_PROVIDER:latest",
    "GEMINI_LIVE_MODEL=GEMINI_LIVE_MODEL:latest",
    "ORG_INTELLIGENCE_OPENAI_MODEL=ORG_INTELLIGENCE_OPENAI_MODEL:latest",
    "ORG_INTELLIGENCE_GEMINI_MAX_OUTPUT_TOKENS=ORG_INTELLIGENCE_GEMINI_MAX_OUTPUT_TOKENS:latest",
    "ORG_INTELLIGENCE_CLAUDE_MAX_TOKENS=ORG_INTELLIGENCE_CLAUDE_MAX_TOKENS:latest",
    "TELNYX_SIP_USERNAME=TELNYX_SIP_USERNAME:latest",
    "TELNYX_SIP_PASSWORD=TELNYX_SIP_PASSWORD:latest",
    "TELNYX_SIP_CONNECTION_ID=TELNYX_SIP_CONNECTION_ID:latest",
    "DEEPGRAM_API_KEY=DEEPGRAM_API_KEY:latest",
    "SECRET_MANAGER_MASTER_KEY=SECRET_MANAGER_MASTER_KEY:latest"
) -join ","

$env_vars = @(
    "DEEPGRAM_MODEL=nova-2-phonecall",
    "DEEPGRAM_LANGUAGE=en-US",
    "NODE_ENV=production",
    "GOOGLE_CLOUD_PROJECT=pivotalb2b-2026",
    "GCP_PROJECT_ID=pivotalb2b-2026"
) -join ","

Write-Host "Deploying with FULLY synced secrets (V2)..."

gcloud run deploy demandgentic-api `
  --source . `
  --region us-central1 `
  --allow-unauthenticated `
  --vpc-connector pivotal-connector `
  --vpc-egress private-ranges-only `
  --set-secrets=$secrets `
  --set-env-vars=$env_vars
