$secrets = @(
    "DATABASE_URL=DATABASE_URL:latest",
    "REDIS_URL=REDIS_URL:latest",
    "OPENAI_API_KEY=OPENAI_API_KEY:latest",
    "TELNYX_API_KEY=TELNYX_API_KEY:latest",
    "TELNYX_SIP_PASSWORD=TELNYX_SIP_PASSWORD:latest",
    "TELNYX_SIP_USERNAME=TELNYX_SIP_USERNAME:latest",
    "TELNYX_SIP_CONNECTION_ID=TELNYX_SIP_CONNECTION_ID:latest",
    "JWT_SECRET=JWT_SECRET:latest",
    "SESSION_SECRET=SESSION_SECRET:latest",
    "PGDATABASE=PGDATABASE:latest",
    "PGHOST=PGHOST:latest",
    "PGPORT=PGPORT:latest",
    "PGUSER=PGUSER:latest",
    "PGPASSWORD=PGPASSWORD:latest",
    "AI_INTEGRATIONS_OPENAI_API_KEY=AI_INTEGRATIONS_OPENAI_API_KEY:latest",
    "AI_INTEGRATIONS_OPENAI_BASE_URL=AI_INTEGRATIONS_OPENAI_BASE_URL:latest",
    "BRAVE_SEARCH_API_KEY=BRAVE_SEARCH_API_KEY:latest",
    "COMPANIES_HOUSE_API_KEY=COMPANIES_HOUSE_API_KEY:latest",
    "DEEPSEEK_API_KEY=DEEPSEEK_API_KEY:latest",
    "ELEVENLABS_API_KEY=ELEVENLABS_API_KEY:latest",
    "ELEVENLABS_WEBHOOK_SECRET=ELEVENLABS_WEBHOOK_SECRET:latest",
    "EMAIL_LIST_VERIFY_API_KEY=EMAIL_LIST_VERIFY_API_KEY:latest",
    "GEMINI_API_KEY=GEMINI_API_KEY:latest",
    "GOOGLE_AUTH_CLIENT_ID=GOOGLE_AUTH_CLIENT_ID:latest",
    "GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest",
    "GOOGLE_SEARCH_API_KEY=GOOGLE_SEARCH_API_KEY:latest",
    "GOOGLE_SEARCH_ENGINE_ID=GOOGLE_SEARCH_ENGINE_ID:latest",
    "MAILGUN_API_KEY=MAILGUN_API_KEY:latest",
    "MAILGUN_DOMAIN=MAILGUN_DOMAIN:latest",
    "MICROSOFT_CLIENT_ID=MICROSOFT_CLIENT_ID:latest",
    "MICROSOFT_CLIENT_SECRET=MICROSOFT_CLIENT_SECRET:latest",
    "MICROSOFT_TENANT_ID=MICROSOFT_TENANT_ID:latest",
    "PUBLIC_WEBSOCKET_URL=PUBLIC_WEBSOCKET_URL:latest",
    "TELNYX_CALL_CONTROL_APP_ID=TELNYX_CALL_CONTROL_APP_ID:latest",
    "TELNYX_FROM_NUMBER=TELNYX_FROM_NUMBER:latest",
    "TELNYX_WEBHOOK_URL=TELNYX_WEBHOOK_URL:latest"
) -join ","

gcloud run deploy demangent-api `
  --source . `
  --region us-central1 `
  --allow-unauthenticated `
  --vpc-connector pivotal-connector `
  --vpc-egress private-ranges-only `
  --set-secrets=$secrets
