import {
  VertexAI,
  FunctionDeclarationSchemaType,
  Part,
} from '@google-cloud/vertexai';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const vertexAI = new VertexAI({
  project: process.env.GCLOUD_PROJECT || 'your-gcp-project-id',
  location: process.env.GCLOUD_LOCATION || 'us-central1',
});

const model = 'gemini-1.5-pro-preview-0409';

// --- 1. Define the Tool for the Agent ---

const getProjectPerformanceData = async (args: { projectId: string }) => {
  console.log(`[Tool] Fetching performance data for project: ${args.projectId}`);
  try {
    const project = await prisma.project.findUnique({
      where: { id: args.projectId },
      include: {
        campaigns: {
          select: {
            name: true,
            type: true,
            leadsGenerated: true,
          },
        },
      },
    });

    if (!project) {
      return { error: `Project with ID ${args.projectId} not found.` };
    }

    const totalLeadsGenerated = project.campaigns.reduce(
      (sum, campaign) => sum + (campaign.leadsGenerated || 0),
      0
    );

    // Structure the data clearly for the AI model
    return {
      projectName: project.clientName,
      leadGoal: project.leadGoal,
      totalLeadsGenerated: totalLeadsGenerated,
      campaigns: project.campaigns,
    };
  } catch (e) {
    console.error('[Tool Error] getProjectPerformanceData:', e);
    return { error: 'Database query for project performance failed.' };
  }
};

const availableTools = {
  getProjectPerformanceData,
};

// --- 2. Define the Tool Schema for the Model ---

const tools = [
  {
    functionDeclarations: [
      {
        name: 'getProjectPerformanceData',
        description:
          'Fetches performance data for a given project, including its overall lead goal and the leads generated by each individual campaign.',
        parameters: {
          type: FunctionDeclarationSchemaType.OBJECT,
          properties: {
            projectId: {
              type: FunctionDeclarationSchemaType.STRING,
              description: 'The unique identifier of the project to analyze.',
            },
          },
          required: ['projectId'],
        },
      },
    ],
  },
];

// --- 3. Create the Main Agentic Function ---

export async function analyzeProjectPerformance(
  userQuestion: string,
  projectId: string
) {
  const generativeModel = vertexAI.getGenerativeModel({ model, tools });
  const chat = generativeModel.startChat();

  const prompt = `You are a professional marketing performance analyst. Your task is to answer the user's question about the performance of project ID '${projectId}'.

    User Question: "${userQuestion}"

    Follow these steps to provide your analysis:
    1. Use the 'getProjectPerformanceData' tool to fetch the latest data for this project.
    2. Analyze the retrieved data to understand the project's progress towards its lead goal. Calculate the percentage of goal achieved.
    3. Identify the best-performing and worst-performing campaigns based on the number of leads generated.
    4. Formulate a clear, data-driven answer to the user's original question. Use specific numbers and percentages to support your analysis.
    5. Structure your final response in clear, easy-to-read Markdown.`;

  console.log(
    `[Agent] Starting analysis for project ${projectId} with question: "${userQuestion}"`
  );

  // This agentic loop will call the tool and then generate a final text response
  let result = await chat.sendMessageStream(prompt);

  for await (const item of result.stream) {
    if (item.candidates?.[0].content.parts[0].functionCall) {
      const call = item.candidates[0].content.parts[0].functionCall;
      console.log('[Agent] Model wants to call function:', call.name);

      // @ts-ignore
      const toolFunction = availableTools[call.name];
      if (toolFunction) {
        const apiResponse = await toolFunction(call.args);
        const response = await chat.sendMessageStream([
          {
            functionResponse: {
              name: call.name,
              response: { name: call.name, content: apiResponse },
            },
          },
        ]);

        // Aggregate the final text response from the model
        let finalResponse = '';
        for await (const finalItem of response.stream) {
          finalResponse += finalItem.candidates?.[0].content.parts[0].text || '';
        }
        console.log('\n[Agent] Final Analysis:\n');
        console.log(finalResponse);
        return { success: true, analysis: finalResponse };
      }
    }
  }

  console.error('[Agent] Model did not request a function call.');
  return { success: false, error: 'Could not interpret the request.' };
}