/**
 * Comprehensive Prompt Registry Seed Script
 *
 * Registers ALL discovered AI prompts across the platform into the centralized
 * prompt_registry table with full metadata: department, function, purpose,
 * AI model, invocation points, and dependency mappings.
 *
 * Run with: npx tsx server/scripts/seed-all-prompts.ts
 *
 * Total: ~130+ prompts across 55+ service files
 */

import { db } from '../db';
import { promptRegistry, promptDependencyMap } from '../../shared/schema';
import { eq } from 'drizzle-orm';

// ==================== PROMPT DEFINITIONS ====================

interface PromptDefinition {
  promptKey: string;
  name: string;
  description: string;
  promptType: 'foundational' | 'system' | 'specialized' | 'template';
  promptScope: 'global' | 'organization' | 'campaign' | 'agent_type';
  agentType?: string;
  category: 'voice' | 'email' | 'intelligence' | 'compliance' | 'system';
  department: 'sales' | 'marketing' | 'operations' | 'ai_engineering' | 'crm' | 'compliance' | 'intelligence' | 'content';
  promptFunction: 'email_drafting' | 'call_script' | 'lead_scoring' | 'enrichment' | 'campaign_personalization' | 'classification' | 'summarization' | 'reasoning' | 'routing' | 'research' | 'content_generation' | 'quality_analysis' | 'disposition' | 'mapping' | 'simulation' | 'image_generation';
  purpose: 'generation' | 'classification' | 'summarization' | 'reasoning' | 'scoring' | 'routing' | 'extraction' | 'analysis' | 'enrichment' | 'personalization' | 'compliance_check' | 'orchestration';
  aiModel: string;
  status: 'live';
  sourceFile: string;
  sourceExport?: string;
  content: string; // Summary description of what the prompt does
  tags: string[];
  invocationPoint: {
    entity: string;
    endpoint?: string;
    serviceLayer: string;
    httpMethod?: string;
  };
  inputDependencies: string[];
  outputDestination: string[];
  dependencies: Array<{
    entityType: 'service' | 'route' | 'script' | 'agent';
    entityName: string;
    endpointPath?: string;
    httpMethod?: string;
    serviceFunction: string;
    direction: 'produces' | 'consumes';
  }>;
}

// ==================== AI SERVICES ====================

const AI_SERVICE_PROMPTS: PromptDefinition[] = [
  // --- Generative Studio (7 prompts) ---
  {
    promptKey: 'generative.landing-page',
    name: 'Landing Page Generator',
    description: 'Generates HTML landing pages with brand-consistent design, CTAs, and responsive layout',
    promptType: 'specialized',
    promptScope: 'organization',
    category: 'system',
    department: 'content',
    promptFunction: 'content_generation',
    purpose: 'generation',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/ai-generative-studio.ts',
    sourceExport: 'generateLandingPage',
    content: 'System prompt for generating HTML landing pages with brand styling, hero sections, feature grids, testimonials, CTAs, and responsive design. Injects organization context and brand messaging.',
    tags: ['generative-studio', 'content', 'landing-page', 'html', 'marketing'],
    invocationPoint: { entity: 'ai-generative-studio', endpoint: '/api/generative-studio/generate', serviceLayer: 'ai-generative-studio', httpMethod: 'POST' },
    inputDependencies: ['organization-context', 'brand-messaging', 'user-prompt', 'content-type'],
    outputDestination: ['generative-studio-projects', 'published-pages'],
    dependencies: [
      { entityType: 'service', entityName: 'ai-generative-studio', serviceFunction: 'generateLandingPage', direction: 'produces' },
      { entityType: 'route', entityName: 'generative-studio-routes', endpointPath: '/api/generative-studio/generate', httpMethod: 'POST', serviceFunction: 'generate', direction: 'consumes' },
    ],
  },
  {
    promptKey: 'generative.email-template',
    name: 'Email Template Generator',
    description: 'Generates professional HTML email templates with responsive design and brand consistency',
    promptType: 'specialized',
    promptScope: 'organization',
    category: 'email',
    department: 'marketing',
    promptFunction: 'email_drafting',
    purpose: 'generation',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/ai-generative-studio.ts',
    sourceExport: 'generateEmail',
    content: 'System prompt for generating HTML email templates with subject lines, preheaders, responsive layouts, and CTA buttons. Uses organization branding.',
    tags: ['generative-studio', 'email', 'template', 'marketing'],
    invocationPoint: { entity: 'ai-generative-studio', endpoint: '/api/generative-studio/generate', serviceLayer: 'ai-generative-studio', httpMethod: 'POST' },
    inputDependencies: ['organization-context', 'brand-messaging', 'user-prompt', 'audience-data'],
    outputDestination: ['generative-studio-projects', 'email-campaigns'],
    dependencies: [
      { entityType: 'service', entityName: 'ai-generative-studio', serviceFunction: 'generateEmail', direction: 'produces' },
      { entityType: 'route', entityName: 'generative-studio-routes', endpointPath: '/api/generative-studio/generate', httpMethod: 'POST', serviceFunction: 'generate', direction: 'consumes' },
    ],
  },
  {
    promptKey: 'generative.blog-post',
    name: 'Blog Post Generator',
    description: 'Generates SEO-optimized blog posts with proper heading hierarchy and markdown formatting',
    promptType: 'specialized',
    promptScope: 'organization',
    category: 'system',
    department: 'content',
    promptFunction: 'content_generation',
    purpose: 'generation',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/ai-generative-studio.ts',
    sourceExport: 'generateBlog',
    content: 'System prompt for generating blog posts with SEO metadata, heading structure, internal linking suggestions, and markdown formatting.',
    tags: ['generative-studio', 'blog', 'content', 'seo'],
    invocationPoint: { entity: 'ai-generative-studio', endpoint: '/api/generative-studio/generate', serviceLayer: 'ai-generative-studio', httpMethod: 'POST' },
    inputDependencies: ['organization-context', 'brand-messaging', 'user-prompt', 'target-keywords'],
    outputDestination: ['generative-studio-projects'],
    dependencies: [
      { entityType: 'service', entityName: 'ai-generative-studio', serviceFunction: 'generateBlog', direction: 'produces' },
    ],
  },
  {
    promptKey: 'generative.ebook',
    name: 'Ebook Generator',
    description: 'Generates multi-chapter ebooks with structured content, executive summaries, and key takeaways',
    promptType: 'specialized',
    promptScope: 'organization',
    category: 'system',
    department: 'content',
    promptFunction: 'content_generation',
    purpose: 'generation',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/ai-generative-studio.ts',
    sourceExport: 'generateEbook',
    content: 'System prompt for generating structured ebook content with chapters, key takeaways, data points, and calls to action.',
    tags: ['generative-studio', 'ebook', 'content', 'long-form'],
    invocationPoint: { entity: 'ai-generative-studio', endpoint: '/api/generative-studio/generate', serviceLayer: 'ai-generative-studio', httpMethod: 'POST' },
    inputDependencies: ['organization-context', 'brand-messaging', 'user-prompt', 'topic'],
    outputDestination: ['generative-studio-projects'],
    dependencies: [
      { entityType: 'service', entityName: 'ai-generative-studio', serviceFunction: 'generateEbook', direction: 'produces' },
    ],
  },
  {
    promptKey: 'generative.solution-brief',
    name: 'Solution Brief Generator',
    description: 'Generates concise solution briefs with problem-solution-benefit structure',
    promptType: 'specialized',
    promptScope: 'organization',
    category: 'system',
    department: 'content',
    promptFunction: 'content_generation',
    purpose: 'generation',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/ai-generative-studio.ts',
    sourceExport: 'generateSolutionBrief',
    content: 'System prompt for generating solution briefs with challenge identification, solution overview, key benefits, and implementation approach.',
    tags: ['generative-studio', 'solution-brief', 'content', 'sales-enablement'],
    invocationPoint: { entity: 'ai-generative-studio', endpoint: '/api/generative-studio/generate', serviceLayer: 'ai-generative-studio', httpMethod: 'POST' },
    inputDependencies: ['organization-context', 'brand-messaging', 'user-prompt'],
    outputDestination: ['generative-studio-projects'],
    dependencies: [
      { entityType: 'service', entityName: 'ai-generative-studio', serviceFunction: 'generateSolutionBrief', direction: 'produces' },
    ],
  },
  {
    promptKey: 'generative.chat',
    name: 'Generative Studio Chat',
    description: 'Interactive AI chat for content brainstorming and refinement within Generative Studio',
    promptType: 'system',
    promptScope: 'organization',
    category: 'system',
    department: 'content',
    promptFunction: 'content_generation',
    purpose: 'generation',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/ai-generative-studio.ts',
    sourceExport: 'chatWithAI',
    content: 'System prompt for interactive chat that helps users brainstorm, refine, and iterate on content within the Generative Studio.',
    tags: ['generative-studio', 'chat', 'interactive', 'content'],
    invocationPoint: { entity: 'ai-generative-studio', endpoint: '/api/generative-studio/chat', serviceLayer: 'ai-generative-studio', httpMethod: 'POST' },
    inputDependencies: ['organization-context', 'chat-history', 'project-context'],
    outputDestination: ['generative-studio-chat-messages'],
    dependencies: [
      { entityType: 'service', entityName: 'ai-generative-studio', serviceFunction: 'chatWithAI', direction: 'produces' },
      { entityType: 'route', entityName: 'generative-studio-routes', endpointPath: '/api/generative-studio/chat', httpMethod: 'POST', serviceFunction: 'chat', direction: 'consumes' },
    ],
  },
  {
    promptKey: 'generative.refine',
    name: 'Content Refinement',
    description: 'Refines and improves existing generated content based on user feedback',
    promptType: 'specialized',
    promptScope: 'organization',
    category: 'system',
    department: 'content',
    promptFunction: 'content_generation',
    purpose: 'generation',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/ai-generative-studio.ts',
    sourceExport: 'refineContent',
    content: 'System prompt for refining previously generated content based on user instructions while maintaining brand consistency.',
    tags: ['generative-studio', 'refine', 'content', 'editing'],
    invocationPoint: { entity: 'ai-generative-studio', endpoint: '/api/generative-studio/refine', serviceLayer: 'ai-generative-studio', httpMethod: 'POST' },
    inputDependencies: ['original-content', 'refinement-instructions', 'organization-context'],
    outputDestination: ['generative-studio-projects'],
    dependencies: [
      { entityType: 'service', entityName: 'ai-generative-studio', serviceFunction: 'refineContent', direction: 'produces' },
    ],
  },

  // --- Account Enrichment (2 prompts) ---
  {
    promptKey: 'enrichment.account',
    name: 'Account Enrichment',
    description: 'Enriches account data with AI-generated insights from web research and company analysis',
    promptType: 'specialized',
    promptScope: 'global',
    category: 'intelligence',
    department: 'intelligence',
    promptFunction: 'enrichment',
    purpose: 'enrichment',
    aiModel: 'gpt-4o-mini',
    status: 'live',
    sourceFile: 'server/services/ai-account-enrichment.ts',
    sourceExport: 'enrichAccount',
    content: 'System prompt for analyzing company data and generating structured enrichment including industry classification, company size estimation, technology stack inference, and competitive positioning.',
    tags: ['enrichment', 'account', 'intelligence', 'research'],
    invocationPoint: { entity: 'ai-account-enrichment', endpoint: '/api/accounts/:id/enrich', serviceLayer: 'ai-account-enrichment', httpMethod: 'POST' },
    inputDependencies: ['account-data', 'company-website', 'existing-contacts'],
    outputDestination: ['accounts-table', 'account-intelligence'],
    dependencies: [
      { entityType: 'service', entityName: 'ai-account-enrichment', serviceFunction: 'enrichAccount', direction: 'produces' },
    ],
  },
  {
    promptKey: 'enrichment.account-insights',
    name: 'Account Insights Generator',
    description: 'Generates strategic insights and engagement recommendations for accounts',
    promptType: 'specialized',
    promptScope: 'global',
    category: 'intelligence',
    department: 'intelligence',
    promptFunction: 'enrichment',
    purpose: 'analysis',
    aiModel: 'gpt-4o-mini',
    status: 'live',
    sourceFile: 'server/services/ai-account-enrichment.ts',
    sourceExport: 'generateInsights',
    content: 'System prompt for generating strategic account insights including engagement opportunities, pain points, and recommended approaches.',
    tags: ['enrichment', 'insights', 'account', 'strategy'],
    invocationPoint: { entity: 'ai-account-enrichment', endpoint: '/api/accounts/:id/insights', serviceLayer: 'ai-account-enrichment', httpMethod: 'POST' },
    inputDependencies: ['account-data', 'enrichment-data', 'campaign-context'],
    outputDestination: ['account-intelligence', 'call-briefs'],
    dependencies: [
      { entityType: 'service', entityName: 'ai-account-enrichment', serviceFunction: 'generateInsights', direction: 'produces' },
    ],
  },

  // --- AE Assignment (1 prompt) ---
  {
    promptKey: 'sales.ae-assignment',
    name: 'AE Account Assignment',
    description: 'AI-driven matching of accounts to account executives based on expertise, capacity, and fit',
    promptType: 'specialized',
    promptScope: 'organization',
    category: 'intelligence',
    department: 'sales',
    promptFunction: 'routing',
    purpose: 'routing',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/ai-ae-assignment.ts',
    sourceExport: 'assignAccountsToAEs',
    content: 'System prompt for intelligently assigning pipeline accounts to account executives based on AE expertise, territory, capacity, and account characteristics.',
    tags: ['sales', 'assignment', 'ae', 'routing', 'pipeline'],
    invocationPoint: { entity: 'ai-ae-assignment', endpoint: '/api/pipeline-accounts/assign', serviceLayer: 'ai-ae-assignment', httpMethod: 'POST' },
    inputDependencies: ['pipeline-accounts', 'ae-profiles', 'assignment-criteria'],
    outputDestination: ['pipeline-accounts-table', 'ae-assignment-batches'],
    dependencies: [
      { entityType: 'service', entityName: 'ai-ae-assignment', serviceFunction: 'assignAccountsToAEs', direction: 'produces' },
      { entityType: 'route', entityName: 'pipeline-accounts-routes', endpointPath: '/api/pipeline-accounts/assign', httpMethod: 'POST', serviceFunction: 'assign', direction: 'consumes' },
    ],
  },

  // --- Disposition Intelligence (2 prompts) ---
  {
    promptKey: 'operations.disposition-analysis',
    name: 'Disposition Analysis',
    description: 'Analyzes call dispositions to classify outcomes and extract intelligence from call results',
    promptType: 'specialized',
    promptScope: 'global',
    category: 'intelligence',
    department: 'operations',
    promptFunction: 'disposition',
    purpose: 'classification',
    aiModel: 'gpt-4o-mini',
    status: 'live',
    sourceFile: 'server/services/ai-disposition-intelligence.ts',
    sourceExport: 'analyzeDisposition',
    content: 'System prompt for analyzing call disposition data to classify call outcomes, identify patterns, and generate actionable intelligence for campaign optimization.',
    tags: ['disposition', 'analysis', 'operations', 'classification'],
    invocationPoint: { entity: 'ai-disposition-intelligence', serviceLayer: 'ai-disposition-intelligence' },
    inputDependencies: ['call-transcript', 'disposition-data', 'campaign-context'],
    outputDestination: ['call-attempts', 'campaign-analytics'],
    dependencies: [
      { entityType: 'service', entityName: 'ai-disposition-intelligence', serviceFunction: 'analyzeDisposition', direction: 'produces' },
    ],
  },
  {
    promptKey: 'operations.disposition-classification',
    name: 'Disposition Classifier',
    description: 'Classifies call outcomes into standardized disposition categories',
    promptType: 'specialized',
    promptScope: 'global',
    category: 'intelligence',
    department: 'operations',
    promptFunction: 'disposition',
    purpose: 'classification',
    aiModel: 'gpt-4o-mini',
    status: 'live',
    sourceFile: 'server/services/ai-disposition-intelligence.ts',
    sourceExport: 'classifyOutcome',
    content: 'System prompt for classifying call outcomes into standardized categories (qualified, not interested, callback, wrong person, etc.) based on transcript analysis.',
    tags: ['disposition', 'classification', 'operations'],
    invocationPoint: { entity: 'ai-disposition-intelligence', serviceLayer: 'ai-disposition-intelligence' },
    inputDependencies: ['call-transcript', 'call-metadata'],
    outputDestination: ['call-attempts', 'leads'],
    dependencies: [
      { entityType: 'service', entityName: 'ai-disposition-intelligence', serviceFunction: 'classifyOutcome', direction: 'produces' },
    ],
  },

  // --- QA Analyzer (1 prompt) ---
  {
    promptKey: 'operations.qa-analysis',
    name: 'Call Quality Analyzer',
    description: 'Analyzes call quality with scoring across multiple dimensions (compliance, engagement, technique)',
    promptType: 'specialized',
    promptScope: 'global',
    category: 'compliance',
    department: 'operations',
    promptFunction: 'quality_analysis',
    purpose: 'scoring',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/ai-qa-analyzer.ts',
    sourceExport: 'analyzeCallQuality',
    content: 'System prompt for comprehensive call quality analysis scoring compliance adherence, engagement techniques, objection handling, information gathering, and overall effectiveness.',
    tags: ['qa', 'quality', 'analysis', 'scoring', 'compliance'],
    invocationPoint: { entity: 'ai-qa-analyzer', serviceLayer: 'ai-qa-analyzer' },
    inputDependencies: ['call-transcript', 'call-metadata', 'campaign-rules'],
    outputDestination: ['qa-scores', 'call-attempts'],
    dependencies: [
      { entityType: 'service', entityName: 'ai-qa-analyzer', serviceFunction: 'analyzeCallQuality', direction: 'produces' },
    ],
  },

  // --- Image Generator (1 prompt) ---
  {
    promptKey: 'generative.image',
    name: 'Image Generator',
    description: 'Generates images using DALL-E for marketing materials and content',
    promptType: 'specialized',
    promptScope: 'organization',
    category: 'system',
    department: 'content',
    promptFunction: 'image_generation',
    purpose: 'generation',
    aiModel: 'dall-e-3',
    status: 'live',
    sourceFile: 'server/services/ai-image-generator.ts',
    sourceExport: 'generateImage',
    content: 'Image generation prompt for creating brand-aligned visuals including hero images, social media graphics, and marketing materials.',
    tags: ['generative-studio', 'image', 'dall-e', 'visual'],
    invocationPoint: { entity: 'ai-image-generator', endpoint: '/api/generative-studio/generate-image', serviceLayer: 'ai-image-generator', httpMethod: 'POST' },
    inputDependencies: ['user-prompt', 'brand-guidelines', 'image-style'],
    outputDestination: ['generative-studio-projects'],
    dependencies: [
      { entityType: 'service', entityName: 'ai-image-generator', serviceFunction: 'generateImage', direction: 'produces' },
    ],
  },

  // --- Demand Runners (6 prompts) ---
  {
    promptKey: 'demand.intel-research',
    name: 'Demand Intel - Research Prompt',
    description: 'Research-focused demand intelligence agent for gathering account and market insights',
    promptType: 'foundational',
    promptScope: 'campaign',
    agentType: 'voice',
    category: 'intelligence',
    department: 'intelligence',
    promptFunction: 'research',
    purpose: 'extraction',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/demand-intel-runner.ts',
    sourceExport: 'buildDemandIntelPrompt',
    content: 'Foundation prompt for Demand Intel agents that conduct research-oriented calls to gather market intelligence, validate account data, and identify decision-makers.',
    tags: ['demand-intel', 'research', 'intelligence', 'voice'],
    invocationPoint: { entity: 'demand-intel-runner', serviceLayer: 'demand-intel-runner' },
    inputDependencies: ['account-data', 'contact-data', 'research-objectives', 'campaign-context'],
    outputDestination: ['call-transcripts', 'account-intelligence', 'leads'],
    dependencies: [
      { entityType: 'service', entityName: 'demand-intel-runner', serviceFunction: 'buildDemandIntelPrompt', direction: 'produces' },
    ],
  },
  {
    promptKey: 'demand.intel-system',
    name: 'Demand Intel - System Instructions',
    description: 'System-level instructions for demand intelligence agent behavior and compliance',
    promptType: 'system',
    promptScope: 'campaign',
    agentType: 'voice',
    category: 'intelligence',
    department: 'intelligence',
    promptFunction: 'call_script',
    purpose: 'orchestration',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/demand-intel-runner.ts',
    sourceExport: 'systemInstructions',
    content: 'System instructions governing Demand Intel agent behavior including conversation flow, compliance rules, and data collection requirements.',
    tags: ['demand-intel', 'system', 'voice', 'compliance'],
    invocationPoint: { entity: 'demand-intel-runner', serviceLayer: 'demand-intel-runner' },
    inputDependencies: ['campaign-rules', 'compliance-requirements'],
    outputDestination: ['voice-agent-runtime'],
    dependencies: [
      { entityType: 'service', entityName: 'demand-intel-runner', serviceFunction: 'getSystemInstructions', direction: 'produces' },
    ],
  },
  {
    promptKey: 'demand.qual-qualification',
    name: 'Demand Qual - Qualification Prompt',
    description: 'Qualification-focused demand agent for lead scoring and opportunity validation',
    promptType: 'foundational',
    promptScope: 'campaign',
    agentType: 'voice',
    category: 'voice',
    department: 'sales',
    promptFunction: 'lead_scoring',
    purpose: 'scoring',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/demand-qual-runner.ts',
    sourceExport: 'buildDemandQualPrompt',
    content: 'Foundation prompt for Demand Qual agents that qualify leads through structured conversations, scoring interest level, budget authority, need, and timeline (BANT).',
    tags: ['demand-qual', 'qualification', 'sales', 'voice', 'bant'],
    invocationPoint: { entity: 'demand-qual-runner', serviceLayer: 'demand-qual-runner' },
    inputDependencies: ['account-data', 'contact-data', 'qualification-criteria', 'campaign-context'],
    outputDestination: ['leads', 'call-transcripts', 'qualification-scores'],
    dependencies: [
      { entityType: 'service', entityName: 'demand-qual-runner', serviceFunction: 'buildDemandQualPrompt', direction: 'produces' },
    ],
  },
  {
    promptKey: 'demand.qual-system',
    name: 'Demand Qual - System Instructions',
    description: 'System-level instructions for demand qualification agent behavior',
    promptType: 'system',
    promptScope: 'campaign',
    agentType: 'voice',
    category: 'voice',
    department: 'sales',
    promptFunction: 'call_script',
    purpose: 'orchestration',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/demand-qual-runner.ts',
    sourceExport: 'systemInstructions',
    content: 'System instructions governing Demand Qual agent behavior including qualification methodology, objection handling, and meeting scheduling.',
    tags: ['demand-qual', 'system', 'voice', 'qualification'],
    invocationPoint: { entity: 'demand-qual-runner', serviceLayer: 'demand-qual-runner' },
    inputDependencies: ['campaign-rules', 'qualification-framework'],
    outputDestination: ['voice-agent-runtime'],
    dependencies: [
      { entityType: 'service', entityName: 'demand-qual-runner', serviceFunction: 'getSystemInstructions', direction: 'produces' },
    ],
  },
  {
    promptKey: 'demand.engage-outreach',
    name: 'Demand Engage - Outreach Prompt',
    description: 'Engagement-focused demand agent for initial outreach and interest generation',
    promptType: 'foundational',
    promptScope: 'campaign',
    agentType: 'voice',
    category: 'voice',
    department: 'sales',
    promptFunction: 'call_script',
    purpose: 'generation',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/demand-engage-runner.ts',
    sourceExport: 'buildDemandEngagePrompt',
    content: 'Foundation prompt for Demand Engage agents that conduct initial outreach calls to generate interest, deliver value propositions, and identify opportunities.',
    tags: ['demand-engage', 'outreach', 'sales', 'voice'],
    invocationPoint: { entity: 'demand-engage-runner', serviceLayer: 'demand-engage-runner' },
    inputDependencies: ['account-data', 'contact-data', 'value-proposition', 'campaign-context'],
    outputDestination: ['call-transcripts', 'leads', 'opportunities'],
    dependencies: [
      { entityType: 'service', entityName: 'demand-engage-runner', serviceFunction: 'buildDemandEngagePrompt', direction: 'produces' },
    ],
  },
  {
    promptKey: 'demand.engage-system',
    name: 'Demand Engage - System Instructions',
    description: 'System-level instructions for demand engagement agent behavior',
    promptType: 'system',
    promptScope: 'campaign',
    agentType: 'voice',
    category: 'voice',
    department: 'sales',
    promptFunction: 'call_script',
    purpose: 'orchestration',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/demand-engage-runner.ts',
    sourceExport: 'systemInstructions',
    content: 'System instructions governing Demand Engage agent behavior including conversation openers, value delivery, and follow-up scheduling.',
    tags: ['demand-engage', 'system', 'voice', 'outreach'],
    invocationPoint: { entity: 'demand-engage-runner', serviceLayer: 'demand-engage-runner' },
    inputDependencies: ['campaign-rules', 'messaging-framework'],
    outputDestination: ['voice-agent-runtime'],
    dependencies: [
      { entityType: 'service', entityName: 'demand-engage-runner', serviceFunction: 'getSystemInstructions', direction: 'produces' },
    ],
  },

  // --- Analyzers & Processors (6 prompts) ---
  {
    promptKey: 'operations.disposition-deep-reanalysis',
    name: 'Disposition Deep Reanalyzer',
    description: 'Deep reanalysis of call dispositions using full transcript review for quality assurance',
    promptType: 'specialized',
    promptScope: 'global',
    category: 'intelligence',
    department: 'operations',
    promptFunction: 'disposition',
    purpose: 'analysis',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/disposition-deep-reanalyzer.ts',
    sourceExport: 'deepReanalyze',
    content: 'System prompt for deep reanalysis of call dispositions, reviewing full transcripts to validate or correct initial disposition classifications.',
    tags: ['disposition', 'reanalysis', 'quality', 'operations'],
    invocationPoint: { entity: 'disposition-deep-reanalyzer', serviceLayer: 'disposition-deep-reanalyzer' },
    inputDependencies: ['call-transcript', 'original-disposition', 'campaign-context'],
    outputDestination: ['call-attempts', 'leads', 'qa-reviews'],
    dependencies: [
      { entityType: 'service', entityName: 'disposition-deep-reanalyzer', serviceFunction: 'deepReanalyze', direction: 'produces' },
    ],
  },
  {
    promptKey: 'operations.post-call-analysis',
    name: 'Post-Call Analyzer',
    description: 'Comprehensive post-call analysis generating summaries, action items, and follow-up recommendations',
    promptType: 'specialized',
    promptScope: 'global',
    category: 'intelligence',
    department: 'operations',
    promptFunction: 'summarization',
    purpose: 'summarization',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/post-call-analyzer.ts',
    sourceExport: 'analyzeCall',
    content: 'System prompt for post-call analysis that generates call summaries, key topics discussed, sentiment analysis, action items, and follow-up recommendations.',
    tags: ['post-call', 'analysis', 'summary', 'operations'],
    invocationPoint: { entity: 'post-call-analyzer', serviceLayer: 'post-call-analyzer' },
    inputDependencies: ['call-transcript', 'call-metadata', 'campaign-context', 'account-data'],
    outputDestination: ['call-summaries', 'action-items', 'leads'],
    dependencies: [
      { entityType: 'service', entityName: 'post-call-analyzer', serviceFunction: 'analyzeCall', direction: 'produces' },
    ],
  },
  {
    promptKey: 'operations.conversation-quality',
    name: 'Conversation Quality Analyzer',
    description: 'Analyzes conversation quality metrics including engagement, rapport, and effectiveness',
    promptType: 'specialized',
    promptScope: 'global',
    category: 'intelligence',
    department: 'operations',
    promptFunction: 'quality_analysis',
    purpose: 'scoring',
    aiModel: 'gpt-4o-mini',
    status: 'live',
    sourceFile: 'server/services/conversation-quality-analyzer.ts',
    sourceExport: 'analyzeQuality',
    content: 'System prompt for analyzing conversation quality dimensions including engagement level, rapport building, information extraction effectiveness, and overall interaction quality.',
    tags: ['quality', 'conversation', 'scoring', 'operations'],
    invocationPoint: { entity: 'conversation-quality-analyzer', serviceLayer: 'conversation-quality-analyzer' },
    inputDependencies: ['call-transcript', 'quality-criteria'],
    outputDestination: ['quality-scores', 'call-attempts'],
    dependencies: [
      { entityType: 'service', entityName: 'conversation-quality-analyzer', serviceFunction: 'analyzeQuality', direction: 'produces' },
    ],
  },

  // --- SMI Agent (8 prompts) ---
  {
    promptKey: 'smi.solution-mapping',
    name: 'SMI - Solution Mapping',
    description: 'Maps organizational solutions to prospect pain points and industry challenges',
    promptType: 'specialized',
    promptScope: 'organization',
    category: 'intelligence',
    department: 'intelligence',
    promptFunction: 'mapping',
    purpose: 'analysis',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/smi-agent/intelligence/solution-mapping-service.ts',
    sourceExport: 'mapSolutions',
    content: 'System prompt for mapping organizational solutions and capabilities to specific prospect pain points, industry challenges, and use cases.',
    tags: ['smi', 'solution-mapping', 'intelligence', 'analysis'],
    invocationPoint: { entity: 'smi-agent', serviceLayer: 'solution-mapping-service' },
    inputDependencies: ['organization-solutions', 'prospect-data', 'industry-context'],
    outputDestination: ['solution-maps', 'call-briefs', 'email-personalization'],
    dependencies: [
      { entityType: 'service', entityName: 'solution-mapping-service', serviceFunction: 'mapSolutions', direction: 'produces' },
    ],
  },
  {
    promptKey: 'smi.contact-intelligence',
    name: 'SMI - Contact Intelligence',
    description: 'Generates contact-level intelligence including role analysis and engagement strategy',
    promptType: 'specialized',
    promptScope: 'organization',
    category: 'intelligence',
    department: 'intelligence',
    promptFunction: 'research',
    purpose: 'analysis',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/smi-agent/intelligence/contact-intelligence.ts',
    sourceExport: 'analyzeContact',
    content: 'System prompt for analyzing contact roles, responsibilities, and decision-making authority to generate personalized engagement strategies.',
    tags: ['smi', 'contact', 'intelligence', 'personalization'],
    invocationPoint: { entity: 'smi-agent', serviceLayer: 'contact-intelligence' },
    inputDependencies: ['contact-data', 'account-data', 'role-hierarchy'],
    outputDestination: ['contact-intelligence', 'call-briefs', 'email-personalization'],
    dependencies: [
      { entityType: 'service', entityName: 'contact-intelligence', serviceFunction: 'analyzeContact', direction: 'produces' },
    ],
  },
  {
    promptKey: 'smi.perspective-engine',
    name: 'SMI - Perspective Engine',
    description: 'Generates multi-perspective viewpoints for approaching prospects based on their role and priorities',
    promptType: 'specialized',
    promptScope: 'organization',
    category: 'intelligence',
    department: 'intelligence',
    promptFunction: 'reasoning',
    purpose: 'reasoning',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/smi-agent/intelligence/perspective-engine.ts',
    sourceExport: 'generatePerspectives',
    content: 'System prompt for generating multiple conversation perspectives (technical, business, strategic) tailored to the prospect role and priorities.',
    tags: ['smi', 'perspective', 'intelligence', 'strategy'],
    invocationPoint: { entity: 'smi-agent', serviceLayer: 'perspective-engine' },
    inputDependencies: ['contact-data', 'account-data', 'solution-mapping', 'industry-context'],
    outputDestination: ['call-briefs', 'conversation-strategies'],
    dependencies: [
      { entityType: 'service', entityName: 'perspective-engine', serviceFunction: 'generatePerspectives', direction: 'produces' },
    ],
  },
  {
    promptKey: 'smi.industry-mapping',
    name: 'SMI - Industry Mapping',
    description: 'Maps accounts to industry verticals and identifies sector-specific challenges',
    promptType: 'specialized',
    promptScope: 'global',
    category: 'intelligence',
    department: 'intelligence',
    promptFunction: 'mapping',
    purpose: 'classification',
    aiModel: 'gpt-4o-mini',
    status: 'live',
    sourceFile: 'server/services/smi-agent/mapping/industry-mapping-service.ts',
    sourceExport: 'mapIndustry',
    content: 'System prompt for classifying accounts into industry verticals and identifying sector-specific challenges, trends, and opportunities.',
    tags: ['smi', 'industry', 'mapping', 'classification'],
    invocationPoint: { entity: 'smi-agent', serviceLayer: 'industry-mapping-service' },
    inputDependencies: ['account-data', 'company-description'],
    outputDestination: ['account-intelligence', 'industry-classifications'],
    dependencies: [
      { entityType: 'service', entityName: 'industry-mapping-service', serviceFunction: 'mapIndustry', direction: 'produces' },
    ],
  },
  {
    promptKey: 'smi.title-mapping',
    name: 'SMI - Title Mapping',
    description: 'Maps contact titles to standardized roles and identifies decision-making authority',
    promptType: 'specialized',
    promptScope: 'global',
    category: 'intelligence',
    department: 'intelligence',
    promptFunction: 'mapping',
    purpose: 'classification',
    aiModel: 'gpt-4o-mini',
    status: 'live',
    sourceFile: 'server/services/smi-agent/mapping/title-mapping-service.ts',
    sourceExport: 'mapTitle',
    content: 'System prompt for mapping contact job titles to standardized role categories and assessing decision-making authority level.',
    tags: ['smi', 'title', 'mapping', 'classification', 'role'],
    invocationPoint: { entity: 'smi-agent', serviceLayer: 'title-mapping-service' },
    inputDependencies: ['contact-title', 'company-context'],
    outputDestination: ['contact-data', 'role-classifications'],
    dependencies: [
      { entityType: 'service', entityName: 'title-mapping-service', serviceFunction: 'mapTitle', direction: 'produces' },
    ],
  },

  // --- Problem Intelligence (4 prompts) ---
  {
    promptKey: 'intelligence.problem-generation',
    name: 'Problem Generation Engine',
    description: 'Generates industry-specific problem statements and pain points for target accounts',
    promptType: 'specialized',
    promptScope: 'organization',
    category: 'intelligence',
    department: 'intelligence',
    promptFunction: 'research',
    purpose: 'generation',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/problem-intelligence/problem-generation-engine.ts',
    sourceExport: 'generateProblems',
    content: 'System prompt for generating industry-specific problem statements, pain points, and challenges that target accounts likely face, used for personalized outreach.',
    tags: ['problem-intelligence', 'generation', 'pain-points', 'research'],
    invocationPoint: { entity: 'problem-intelligence', serviceLayer: 'problem-generation-engine' },
    inputDependencies: ['industry-data', 'account-data', 'solution-capabilities'],
    outputDestination: ['problem-statements', 'call-briefs', 'email-personalization'],
    dependencies: [
      { entityType: 'service', entityName: 'problem-generation-engine', serviceFunction: 'generateProblems', direction: 'produces' },
    ],
  },
  {
    promptKey: 'intelligence.campaign-package',
    name: 'Campaign Intelligence Package',
    description: 'Assembles comprehensive intelligence packages for campaign execution',
    promptType: 'specialized',
    promptScope: 'campaign',
    category: 'intelligence',
    department: 'intelligence',
    promptFunction: 'research',
    purpose: 'orchestration',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/problem-intelligence/campaign-intelligence-package-service.ts',
    sourceExport: 'buildPackage',
    content: 'System prompt for assembling comprehensive campaign intelligence packages including market research, competitive analysis, and prospect-specific insights.',
    tags: ['campaign', 'intelligence', 'package', 'research'],
    invocationPoint: { entity: 'problem-intelligence', serviceLayer: 'campaign-intelligence-package-service' },
    inputDependencies: ['campaign-data', 'account-lists', 'industry-research', 'solution-mapping'],
    outputDestination: ['campaign-intelligence', 'call-briefs', 'agent-context'],
    dependencies: [
      { entityType: 'service', entityName: 'campaign-intelligence-package-service', serviceFunction: 'buildPackage', direction: 'produces' },
    ],
  },

  // --- Library Services (10 prompts) ---
  {
    promptKey: 'intelligence.org-context',
    name: 'Organization Context Builder',
    description: 'Builds comprehensive organization context for injection into AI agent prompts',
    promptType: 'foundational',
    promptScope: 'organization',
    category: 'system',
    department: 'intelligence',
    promptFunction: 'enrichment',
    purpose: 'orchestration',
    aiModel: 'n/a',
    status: 'live',
    sourceFile: 'server/lib/org-intelligence-helper.ts',
    sourceExport: 'buildAgentSystemPrompt',
    content: 'Core system prompt builder that assembles organization context, campaign context, account intelligence, and compliance rules into a unified system prompt for all AI agents.',
    tags: ['org-intelligence', 'context', 'system', 'foundational'],
    invocationPoint: { entity: 'org-intelligence-helper', serviceLayer: 'org-intelligence-helper' },
    inputDependencies: ['organization-data', 'campaign-data', 'account-data', 'brand-messaging'],
    outputDestination: ['all-ai-agents', 'voice-providers', 'email-agents'],
    dependencies: [
      { entityType: 'service', entityName: 'org-intelligence-helper', serviceFunction: 'buildAgentSystemPrompt', direction: 'produces' },
    ],
  },
  {
    promptKey: 'email.ai-generation',
    name: 'Email AI Service - Generation',
    description: 'Generates personalized email content for campaign outreach',
    promptType: 'specialized',
    promptScope: 'campaign',
    category: 'email',
    department: 'marketing',
    promptFunction: 'email_drafting',
    purpose: 'generation',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/lib/email-ai-service.ts',
    sourceExport: 'generateEmail',
    content: 'System prompt for generating personalized email content for campaign outreach including subject lines, body copy, and CTAs tailored to the recipient.',
    tags: ['email', 'generation', 'campaign', 'personalization'],
    invocationPoint: { entity: 'email-ai-service', serviceLayer: 'email-ai-service' },
    inputDependencies: ['contact-data', 'account-data', 'campaign-context', 'email-template'],
    outputDestination: ['email-queue', 'campaign-emails'],
    dependencies: [
      { entityType: 'service', entityName: 'email-ai-service', serviceFunction: 'generateEmail', direction: 'produces' },
    ],
  },
  {
    promptKey: 'operations.field-matching',
    name: 'AI Field Matcher',
    description: 'Matches CSV import fields to database schema fields using AI inference',
    promptType: 'specialized',
    promptScope: 'global',
    category: 'system',
    department: 'operations',
    promptFunction: 'mapping',
    purpose: 'classification',
    aiModel: 'gpt-4o-mini',
    status: 'live',
    sourceFile: 'server/lib/ai-field-matcher.ts',
    sourceExport: 'matchFields',
    content: 'System prompt for intelligently matching CSV column headers to database schema fields, handling variations in naming conventions and abbreviations.',
    tags: ['field-matching', 'import', 'mapping', 'operations'],
    invocationPoint: { entity: 'ai-field-matcher', serviceLayer: 'ai-field-matcher' },
    inputDependencies: ['csv-headers', 'schema-fields'],
    outputDestination: ['import-mapping', 'data-upload'],
    dependencies: [
      { entityType: 'service', entityName: 'ai-field-matcher', serviceFunction: 'matchFields', direction: 'produces' },
    ],
  },
  {
    promptKey: 'enrichment.company',
    name: 'Company Enrichment',
    description: 'Enriches company data with web research and AI analysis',
    promptType: 'specialized',
    promptScope: 'global',
    category: 'intelligence',
    department: 'intelligence',
    promptFunction: 'enrichment',
    purpose: 'enrichment',
    aiModel: 'gpt-4o-mini',
    status: 'live',
    sourceFile: 'server/lib/company-enrichment.ts',
    sourceExport: 'enrichCompany',
    content: 'System prompt for researching and enriching company data including industry classification, employee count, revenue estimates, and technology stack.',
    tags: ['enrichment', 'company', 'research', 'intelligence'],
    invocationPoint: { entity: 'company-enrichment', serviceLayer: 'company-enrichment' },
    inputDependencies: ['company-name', 'company-website', 'existing-data'],
    outputDestination: ['accounts-table', 'enrichment-data'],
    dependencies: [
      { entityType: 'service', entityName: 'company-enrichment', serviceFunction: 'enrichCompany', direction: 'produces' },
    ],
  },
  {
    promptKey: 'email.deepseek-generation',
    name: 'DeepSeek Email Service',
    description: 'Email generation using DeepSeek model for cost-efficient bulk email content',
    promptType: 'specialized',
    promptScope: 'campaign',
    category: 'email',
    department: 'marketing',
    promptFunction: 'email_drafting',
    purpose: 'generation',
    aiModel: 'deepseek-chat',
    status: 'live',
    sourceFile: 'server/lib/deepseek-email-service.ts',
    sourceExport: 'generateEmail',
    content: 'System prompt for email generation using DeepSeek model, optimized for cost-efficient bulk email content creation with personalization.',
    tags: ['email', 'deepseek', 'generation', 'bulk'],
    invocationPoint: { entity: 'deepseek-email-service', serviceLayer: 'deepseek-email-service' },
    inputDependencies: ['contact-data', 'account-data', 'campaign-context', 'email-template'],
    outputDestination: ['email-queue', 'campaign-emails'],
    dependencies: [
      { entityType: 'service', entityName: 'deepseek-email-service', serviceFunction: 'generateEmail', direction: 'produces' },
    ],
  },
  {
    promptKey: 'enrichment.address',
    name: 'Address Enrichment',
    description: 'Validates and enriches address data using AI inference',
    promptType: 'specialized',
    promptScope: 'global',
    category: 'system',
    department: 'intelligence',
    promptFunction: 'enrichment',
    purpose: 'enrichment',
    aiModel: 'gpt-4o-mini',
    status: 'live',
    sourceFile: 'server/lib/address-enrichment.ts',
    sourceExport: 'enrichAddress',
    content: 'System prompt for validating and enriching address data, standardizing formats, and inferring missing geographic information.',
    tags: ['enrichment', 'address', 'data-quality'],
    invocationPoint: { entity: 'address-enrichment', serviceLayer: 'address-enrichment' },
    inputDependencies: ['address-data', 'company-data'],
    outputDestination: ['accounts-table', 'contacts-table'],
    dependencies: [
      { entityType: 'service', entityName: 'address-enrichment', serviceFunction: 'enrichAddress', direction: 'produces' },
    ],
  },

  // --- Other Services (15 prompts) ---
  {
    promptKey: 'ai-engineering.rule-parser',
    name: 'Natural Language Rule Parser',
    description: 'Parses natural language rules into structured automation conditions',
    promptType: 'specialized',
    promptScope: 'global',
    category: 'system',
    department: 'ai_engineering',
    promptFunction: 'classification',
    purpose: 'extraction',
    aiModel: 'gpt-4o-mini',
    status: 'live',
    sourceFile: 'server/services/natural-language-rule-parser.ts',
    sourceExport: 'parseRule',
    content: 'System prompt for parsing natural language business rules into structured JSON conditions for automation engine execution.',
    tags: ['rule-parser', 'nlp', 'automation', 'ai-engineering'],
    invocationPoint: { entity: 'natural-language-rule-parser', serviceLayer: 'natural-language-rule-parser' },
    inputDependencies: ['natural-language-rule', 'available-fields', 'available-operators'],
    outputDestination: ['automation-rules', 'workflow-conditions'],
    dependencies: [
      { entityType: 'service', entityName: 'natural-language-rule-parser', serviceFunction: 'parseRule', direction: 'produces' },
    ],
  },
  {
    promptKey: 'ai-engineering.agent-brain',
    name: 'Agent Brain Service',
    description: 'Central reasoning engine for the agentic operator system with tool execution',
    promptType: 'foundational',
    promptScope: 'global',
    category: 'system',
    department: 'ai_engineering',
    promptFunction: 'reasoning',
    purpose: 'orchestration',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/agent-brain-service.ts',
    sourceExport: 'processMessage',
    content: 'Foundation prompt for the agentic operator brain that handles natural language commands, plans multi-step actions, and executes tools across the platform.',
    tags: ['agent', 'brain', 'reasoning', 'orchestration', 'agentic-operator'],
    invocationPoint: { entity: 'agent-brain-service', endpoint: '/api/agent-panel/chat', serviceLayer: 'agent-brain-service', httpMethod: 'POST' },
    inputDependencies: ['user-message', 'agent-prompts', 'available-tools', 'conversation-history'],
    outputDestination: ['agent-conversations', 'execution-plans', 'tool-results'],
    dependencies: [
      { entityType: 'service', entityName: 'agent-brain-service', serviceFunction: 'processMessage', direction: 'produces' },
      { entityType: 'route', entityName: 'agent-panel', endpointPath: '/api/agent-panel/chat', httpMethod: 'POST', serviceFunction: 'chat', direction: 'consumes' },
    ],
  },
  {
    promptKey: 'marketing.account-messaging',
    name: 'Account Messaging Service',
    description: 'Generates personalized messaging frameworks for target accounts',
    promptType: 'specialized',
    promptScope: 'campaign',
    category: 'intelligence',
    department: 'marketing',
    promptFunction: 'campaign_personalization',
    purpose: 'personalization',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/account-messaging-service.ts',
    sourceExport: 'generateMessaging',
    content: 'System prompt for generating personalized messaging frameworks for accounts including value propositions, pain point narratives, and conversation starters.',
    tags: ['messaging', 'account', 'personalization', 'marketing'],
    invocationPoint: { entity: 'account-messaging-service', serviceLayer: 'account-messaging-service' },
    inputDependencies: ['account-data', 'contact-data', 'solution-mapping', 'industry-context'],
    outputDestination: ['account-messaging', 'call-briefs', 'email-templates'],
    dependencies: [
      { entityType: 'service', entityName: 'account-messaging-service', serviceFunction: 'generateMessaging', direction: 'produces' },
    ],
  },
  {
    promptKey: 'sales.account-call-prep',
    name: 'Account Call Preparation',
    description: 'Prepares call briefs and talking points for account outreach calls',
    promptType: 'specialized',
    promptScope: 'campaign',
    category: 'voice',
    department: 'sales',
    promptFunction: 'call_script',
    purpose: 'generation',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/account-call-service.ts',
    sourceExport: 'prepareCall',
    content: 'System prompt for preparing call briefs with account-specific talking points, objection handling suggestions, and key questions to ask.',
    tags: ['call-prep', 'account', 'sales', 'voice'],
    invocationPoint: { entity: 'account-call-service', serviceLayer: 'account-call-service' },
    inputDependencies: ['account-data', 'contact-data', 'campaign-context', 'call-history'],
    outputDestination: ['call-briefs', 'agent-context'],
    dependencies: [
      { entityType: 'service', entityName: 'account-call-service', serviceFunction: 'prepareCall', direction: 'produces' },
    ],
  },
  {
    promptKey: 'ai-engineering.simulation',
    name: 'Simulation Engine',
    description: 'Simulates AI agent conversations for testing and evaluation',
    promptType: 'specialized',
    promptScope: 'campaign',
    category: 'system',
    department: 'ai_engineering',
    promptFunction: 'simulation',
    purpose: 'generation',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/simulation-engine.ts',
    sourceExport: 'runSimulation',
    content: 'System prompt for simulating AI agent conversations with synthetic prospects for testing, evaluation, and prompt optimization.',
    tags: ['simulation', 'testing', 'evaluation', 'ai-engineering'],
    invocationPoint: { entity: 'simulation-engine', endpoint: '/api/simulations/run', serviceLayer: 'simulation-engine', httpMethod: 'POST' },
    inputDependencies: ['agent-prompt', 'scenario-config', 'campaign-context'],
    outputDestination: ['agent-simulations', 'simulation-results'],
    dependencies: [
      { entityType: 'service', entityName: 'simulation-engine', serviceFunction: 'runSimulation', direction: 'produces' },
      { entityType: 'route', entityName: 'simulations', endpointPath: '/api/simulations/run', httpMethod: 'POST', serviceFunction: 'run', direction: 'consumes' },
    ],
  },
  {
    promptKey: 'intelligence.org-research',
    name: 'Organization Research',
    description: 'Conducts deep research on organizations using web data and AI analysis',
    promptType: 'specialized',
    promptScope: 'global',
    category: 'intelligence',
    department: 'intelligence',
    promptFunction: 'research',
    purpose: 'enrichment',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/organization-research-service.ts',
    sourceExport: 'researchOrganization',
    content: 'System prompt for conducting comprehensive research on target organizations including market position, recent news, strategic initiatives, and growth indicators.',
    tags: ['research', 'organization', 'intelligence', 'enrichment'],
    invocationPoint: { entity: 'organization-research-service', serviceLayer: 'organization-research-service' },
    inputDependencies: ['company-name', 'company-website', 'industry-context'],
    outputDestination: ['organization-intelligence', 'account-data'],
    dependencies: [
      { entityType: 'service', entityName: 'organization-research-service', serviceFunction: 'researchOrganization', direction: 'produces' },
    ],
  },
  {
    promptKey: 'email.routing',
    name: 'Unified Email Router',
    description: 'Routes emails to appropriate handlers based on content classification',
    promptType: 'specialized',
    promptScope: 'global',
    category: 'email',
    department: 'marketing',
    promptFunction: 'routing',
    purpose: 'routing',
    aiModel: 'gpt-4o-mini',
    status: 'live',
    sourceFile: 'server/services/unified-email-router.ts',
    sourceExport: 'routeEmail',
    content: 'System prompt for classifying incoming email content and routing to appropriate response handlers (auto-reply, follow-up, escalation, etc.).',
    tags: ['email', 'routing', 'classification', 'operations'],
    invocationPoint: { entity: 'unified-email-router', serviceLayer: 'unified-email-router' },
    inputDependencies: ['email-content', 'sender-data', 'campaign-context'],
    outputDestination: ['email-responses', 'escalation-queue'],
    dependencies: [
      { entityType: 'service', entityName: 'unified-email-router', serviceFunction: 'routeEmail', direction: 'produces' },
    ],
  },
  {
    promptKey: 'email.prompt-assembly',
    name: 'Email Prompt Service',
    description: 'Assembles email-specific prompts with campaign context and personalization',
    promptType: 'specialized',
    promptScope: 'campaign',
    category: 'email',
    department: 'marketing',
    promptFunction: 'email_drafting',
    purpose: 'orchestration',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/email-prompt-service.ts',
    sourceExport: 'assembleEmailPrompt',
    content: 'System prompt for assembling email-specific prompts by combining campaign context, account intelligence, contact personalization, and brand messaging.',
    tags: ['email', 'prompt-assembly', 'campaign', 'personalization'],
    invocationPoint: { entity: 'email-prompt-service', serviceLayer: 'email-prompt-service' },
    inputDependencies: ['campaign-data', 'account-data', 'contact-data', 'brand-messaging', 'email-template'],
    outputDestination: ['email-generation', 'campaign-emails'],
    dependencies: [
      { entityType: 'service', entityName: 'email-prompt-service', serviceFunction: 'assembleEmailPrompt', direction: 'produces' },
    ],
  },
  {
    promptKey: 'marketing.channel-variants',
    name: 'Channel Variant Generator',
    description: 'Generates prompt variants optimized for different communication channels',
    promptType: 'specialized',
    promptScope: 'campaign',
    category: 'system',
    department: 'marketing',
    promptFunction: 'campaign_personalization',
    purpose: 'generation',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/channel-variant-generator.ts',
    sourceExport: 'generateChannelVariant',
    content: 'System prompt for generating channel-specific prompt variants optimized for voice, email, or text communication modalities.',
    tags: ['channel', 'variant', 'generation', 'marketing'],
    invocationPoint: { entity: 'channel-variant-generator', serviceLayer: 'channel-variant-generator' },
    inputDependencies: ['base-prompt', 'channel-type', 'campaign-context'],
    outputDestination: ['prompt-variants', 'campaign-execution-prompts'],
    dependencies: [
      { entityType: 'service', entityName: 'channel-variant-generator', serviceFunction: 'generateChannelVariant', direction: 'produces' },
    ],
  },

  // --- Prompt Infrastructure (7 prompts) ---
  {
    promptKey: 'ai-engineering.prompt-optimization',
    name: 'Prompt Optimization Pipeline',
    description: 'Analyzes and optimizes prompts based on performance data and best practices',
    promptType: 'specialized',
    promptScope: 'global',
    category: 'system',
    department: 'ai_engineering',
    promptFunction: 'reasoning',
    purpose: 'analysis',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/prompt-optimization-pipeline.ts',
    sourceExport: 'optimizePrompt',
    content: 'System prompt for analyzing prompt performance data and generating optimization suggestions including structure improvements, token efficiency, and clarity enhancements.',
    tags: ['optimization', 'prompt-engineering', 'ai-engineering'],
    invocationPoint: { entity: 'prompt-optimization-pipeline', serviceLayer: 'prompt-optimization-pipeline' },
    inputDependencies: ['prompt-content', 'performance-data', 'call-outcomes'],
    outputDestination: ['optimization-suggestions', 'prompt-variants'],
    dependencies: [
      { entityType: 'service', entityName: 'prompt-optimization-pipeline', serviceFunction: 'optimizePrompt', direction: 'produces' },
    ],
  },
  {
    promptKey: 'ai-engineering.variant-generation',
    name: 'Prompt Variant Generator',
    description: 'Generates prompt variants for A/B testing with different perspectives and approaches',
    promptType: 'specialized',
    promptScope: 'global',
    category: 'system',
    department: 'ai_engineering',
    promptFunction: 'content_generation',
    purpose: 'generation',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/prompt-variant-generator.ts',
    sourceExport: 'generateVariants',
    content: 'System prompt for generating multiple prompt variants with different communication perspectives (consultative, direct value, pain point, social proof, etc.) for A/B testing.',
    tags: ['variant', 'generation', 'ab-testing', 'ai-engineering'],
    invocationPoint: { entity: 'prompt-variant-generator', endpoint: '/api/prompt-variants/generate', serviceLayer: 'prompt-variant-generator', httpMethod: 'POST' },
    inputDependencies: ['base-prompt', 'perspectives', 'campaign-context'],
    outputDestination: ['prompt-variants-table'],
    dependencies: [
      { entityType: 'service', entityName: 'prompt-variant-generator', serviceFunction: 'generateVariants', direction: 'produces' },
      { entityType: 'route', entityName: 'prompt-variants', endpointPath: '/api/prompt-variants/generate', httpMethod: 'POST', serviceFunction: 'generate', direction: 'consumes' },
    ],
  },
  {
    promptKey: 'ai-engineering.prompt-validation',
    name: 'Prompt Validator',
    description: 'Validates prompt quality, safety, and compliance before deployment',
    promptType: 'specialized',
    promptScope: 'global',
    category: 'compliance',
    department: 'ai_engineering',
    promptFunction: 'quality_analysis',
    purpose: 'compliance_check',
    aiModel: 'gpt-4o-mini',
    status: 'live',
    sourceFile: 'server/services/prompt-validator.ts',
    sourceExport: 'validatePrompt',
    content: 'System prompt for validating prompt content against safety guidelines, compliance requirements, and quality standards before deployment.',
    tags: ['validation', 'compliance', 'quality', 'ai-engineering'],
    invocationPoint: { entity: 'prompt-validator', serviceLayer: 'prompt-validator' },
    inputDependencies: ['prompt-content', 'compliance-rules', 'quality-criteria'],
    outputDestination: ['validation-results', 'prompt-registry'],
    dependencies: [
      { entityType: 'service', entityName: 'prompt-validator', serviceFunction: 'validatePrompt', direction: 'produces' },
    ],
  },
  {
    promptKey: 'ai-engineering.test-evaluator',
    name: 'Prompt Test Evaluator',
    description: 'Evaluates prompt test results and scores agent conversation quality',
    promptType: 'specialized',
    promptScope: 'global',
    category: 'system',
    department: 'ai_engineering',
    promptFunction: 'quality_analysis',
    purpose: 'scoring',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/prompt-testing/evaluator.ts',
    sourceExport: 'evaluateConversation',
    content: 'System prompt for evaluating simulated conversation quality, scoring adherence to prompt instructions, engagement effectiveness, and goal achievement.',
    tags: ['testing', 'evaluation', 'scoring', 'ai-engineering'],
    invocationPoint: { entity: 'prompt-testing', serviceLayer: 'prompt-testing/evaluator' },
    inputDependencies: ['conversation-transcript', 'evaluation-criteria', 'prompt-content'],
    outputDestination: ['test-results', 'prompt-variant-tests'],
    dependencies: [
      { entityType: 'service', entityName: 'prompt-testing-evaluator', serviceFunction: 'evaluateConversation', direction: 'produces' },
    ],
  },
  {
    promptKey: 'ai-engineering.test-prospect',
    name: 'Prompt Test Prospect Agent',
    description: 'Simulates prospect behavior for testing agent prompts',
    promptType: 'specialized',
    promptScope: 'global',
    category: 'system',
    department: 'ai_engineering',
    promptFunction: 'simulation',
    purpose: 'generation',
    aiModel: 'gpt-4o',
    status: 'live',
    sourceFile: 'server/services/prompt-testing/prospect-agent.ts',
    sourceExport: 'simulateProspect',
    content: 'System prompt for simulating realistic prospect behavior with varying personalities, objections, and engagement levels for agent testing.',
    tags: ['testing', 'simulation', 'prospect', 'ai-engineering'],
    invocationPoint: { entity: 'prompt-testing', serviceLayer: 'prompt-testing/prospect-agent' },
    inputDependencies: ['prospect-scenario', 'persona-config', 'objection-scripts'],
    outputDestination: ['test-transcripts', 'simulation-results'],
    dependencies: [
      { entityType: 'service', entityName: 'prompt-testing-prospect-agent', serviceFunction: 'simulateProspect', direction: 'produces' },
    ],
  },

  // --- DeepSeek Client (1 prompt) ---
  {
    promptKey: 'ai-engineering.deepseek-client',
    name: 'DeepSeek Client',
    description: 'General-purpose DeepSeek model client for cost-efficient AI operations',
    promptType: 'system',
    promptScope: 'global',
    category: 'system',
    department: 'ai_engineering',
    promptFunction: 'reasoning',
    purpose: 'generation',
    aiModel: 'deepseek-chat',
    status: 'live',
    sourceFile: 'server/services/deepseek-client.ts',
    sourceExport: 'chat',
    content: 'General-purpose system prompt interface for DeepSeek model used for cost-efficient AI operations across the platform.',
    tags: ['deepseek', 'client', 'general', 'ai-engineering'],
    invocationPoint: { entity: 'deepseek-client', serviceLayer: 'deepseek-client' },
    inputDependencies: ['user-prompt', 'system-context'],
    outputDestination: ['various-services'],
    dependencies: [
      { entityType: 'service', entityName: 'deepseek-client', serviceFunction: 'chat', direction: 'produces' },
    ],
  },

  // --- Voice Provider Prompts (4 prompts) ---
  {
    promptKey: 'voice.gemini-live-setup',
    name: 'Gemini Live Provider - Setup',
    description: 'System prompt and configuration for Gemini Live voice provider WebSocket sessions',
    promptType: 'foundational',
    promptScope: 'campaign',
    agentType: 'voice',
    category: 'voice',
    department: 'sales',
    promptFunction: 'call_script',
    purpose: 'orchestration',
    aiModel: 'gemini-2.5-flash',
    status: 'live',
    sourceFile: 'server/services/voice-providers/gemini-live-provider.ts',
    sourceExport: 'setupSession',
    content: 'WebSocket setup configuration and system instruction for Gemini Live voice sessions including voice control, compliance rules, and conversation management.',
    tags: ['voice', 'gemini', 'provider', 'setup', 'realtime'],
    invocationPoint: { entity: 'gemini-live-provider', serviceLayer: 'gemini-live-provider' },
    inputDependencies: ['system-prompt', 'voice-config', 'tool-definitions', 'campaign-context'],
    outputDestination: ['gemini-websocket-session'],
    dependencies: [
      { entityType: 'service', entityName: 'gemini-live-provider', serviceFunction: 'setupSession', direction: 'consumes' },
    ],
  },
  {
    promptKey: 'voice.openai-realtime-setup',
    name: 'OpenAI Realtime Provider - Setup',
    description: 'System prompt and configuration for OpenAI Realtime voice provider sessions',
    promptType: 'foundational',
    promptScope: 'campaign',
    agentType: 'voice',
    category: 'voice',
    department: 'sales',
    promptFunction: 'call_script',
    purpose: 'orchestration',
    aiModel: 'gpt-4o-realtime',
    status: 'live',
    sourceFile: 'server/services/voice-providers/openai-realtime-provider.ts',
    sourceExport: 'setupSession',
    content: 'WebSocket setup configuration and instructions for OpenAI Realtime voice sessions including voice parameters, turn detection, and conversation management.',
    tags: ['voice', 'openai', 'provider', 'setup', 'realtime'],
    invocationPoint: { entity: 'openai-realtime-provider', serviceLayer: 'openai-realtime-provider' },
    inputDependencies: ['system-prompt', 'voice-config', 'tool-definitions', 'campaign-context'],
    outputDestination: ['openai-websocket-session'],
    dependencies: [
      { entityType: 'service', entityName: 'openai-realtime-provider', serviceFunction: 'setupSession', direction: 'consumes' },
    ],
  },

  // --- Knowledge & Context Assembly (3 prompts) ---
  {
    promptKey: 'voice.knowledge-assembly',
    name: 'Knowledge Assembly Service',
    description: 'Assembles multi-layer knowledge blocks into runtime voice agent prompts',
    promptType: 'foundational',
    promptScope: 'campaign',
    agentType: 'voice',
    category: 'voice',
    department: 'ai_engineering',
    promptFunction: 'call_script',
    purpose: 'orchestration',
    aiModel: 'n/a',
    status: 'live',
    sourceFile: 'server/services/knowledge-assembly-service.ts',
    sourceExport: 'assembleKnowledge',
    content: 'Assembles knowledge blocks from Layer 1 (Universal), Layer 2 (Organization), and Layer 3 (Campaign) into a complete runtime prompt for voice agents.',
    tags: ['knowledge', 'assembly', 'layers', 'voice', 'runtime'],
    invocationPoint: { entity: 'knowledge-assembly-service', serviceLayer: 'knowledge-assembly-service' },
    inputDependencies: ['knowledge-blocks', 'agent-config', 'campaign-config'],
    outputDestination: ['voice-agent-runtime', 'prompt-execution-logs'],
    dependencies: [
      { entityType: 'service', entityName: 'knowledge-assembly-service', serviceFunction: 'assembleKnowledge', direction: 'produces' },
    ],
  },
  {
    promptKey: 'voice.unified-call-context',
    name: 'Unified Call Context',
    description: 'Builds unified call context with account, contact, and campaign data for voice agents',
    promptType: 'specialized',
    promptScope: 'campaign',
    agentType: 'voice',
    category: 'voice',
    department: 'sales',
    promptFunction: 'call_script',
    purpose: 'orchestration',
    aiModel: 'n/a',
    status: 'live',
    sourceFile: 'server/services/unified-call-context.ts',
    sourceExport: 'buildCallContext',
    content: 'Builds comprehensive call context by assembling account intelligence, contact data, call history, campaign objectives, and compliance rules.',
    tags: ['call-context', 'voice', 'account', 'personalization'],
    invocationPoint: { entity: 'unified-call-context', serviceLayer: 'unified-call-context' },
    inputDependencies: ['account-data', 'contact-data', 'call-history', 'campaign-data'],
    outputDestination: ['voice-agent-runtime', 'call-briefs'],
    dependencies: [
      { entityType: 'service', entityName: 'unified-call-context', serviceFunction: 'buildCallContext', direction: 'produces' },
    ],
  },
  {
    promptKey: 'voice.provider-prompt-assembly',
    name: 'Provider Prompt Assembly',
    description: 'Assembles provider-specific prompts adapting content for Gemini, OpenAI, or other providers',
    promptType: 'foundational',
    promptScope: 'campaign',
    agentType: 'voice',
    category: 'voice',
    department: 'ai_engineering',
    promptFunction: 'call_script',
    purpose: 'orchestration',
    aiModel: 'varies',
    status: 'live',
    sourceFile: 'server/services/provider-prompt-assembly.ts',
    sourceExport: 'assembleProviderPrompt',
    content: 'Adapts assembled prompts for specific AI providers, handling format differences between Gemini (camelCase) and OpenAI (snake_case) configurations.',
    tags: ['provider', 'assembly', 'voice', 'adaptation'],
    invocationPoint: { entity: 'provider-prompt-assembly', serviceLayer: 'provider-prompt-assembly' },
    inputDependencies: ['assembled-prompt', 'provider-type', 'voice-config'],
    outputDestination: ['voice-provider-session'],
    dependencies: [
      { entityType: 'service', entityName: 'provider-prompt-assembly', serviceFunction: 'assembleProviderPrompt', direction: 'produces' },
    ],
  },
];

// ==================== SEED FUNCTION ====================

async function seedAllPrompts() {
  console.log('=== Comprehensive Prompt Registry Seed ===\n');

  const allPrompts = AI_SERVICE_PROMPTS;

  let created = 0;
  let updated = 0;
  let skipped = 0;
  let depCreated = 0;

  for (const def of allPrompts) {
    try {
      // Check if prompt already exists
      const [existing] = await db.select()
        .from(promptRegistry)
        .where(eq(promptRegistry.promptKey, def.promptKey))
        .limit(1);

      if (existing) {
        // Update metadata fields if they're new
        const needsUpdate = !existing.department || !existing.promptFunction || !existing.purpose;
        if (needsUpdate) {
          await db.update(promptRegistry)
            .set({
              department: def.department,
              promptFunction: def.promptFunction,
              purpose: def.purpose,
              aiModel: def.aiModel,
              status: def.status,
              invocationPoint: def.invocationPoint,
              inputDependencies: def.inputDependencies,
              outputDestination: def.outputDestination,
              sourceFile: def.sourceFile,
              sourceExport: def.sourceExport,
              tags: def.tags,
              updatedAt: new Date(),
            })
            .where(eq(promptRegistry.id, existing.id));
          updated++;
          console.log(`  Updated: ${def.promptKey}`);
        } else {
          skipped++;
        }
      } else {
        // Create new prompt
        const [inserted] = await db.insert(promptRegistry)
          .values({
            promptKey: def.promptKey,
            name: def.name,
            description: def.description,
            promptType: def.promptType,
            promptScope: def.promptScope,
            agentType: def.agentType || null,
            category: def.category,
            content: def.content,
            defaultContent: def.content,
            isActive: true,
            isLocked: false,
            priority: 50,
            tags: def.tags,
            sourceFile: def.sourceFile,
            sourceExport: def.sourceExport,
            department: def.department,
            promptFunction: def.promptFunction,
            purpose: def.purpose,
            aiModel: def.aiModel,
            status: def.status,
            invocationPoint: def.invocationPoint,
            inputDependencies: def.inputDependencies,
            outputDestination: def.outputDestination,
          })
          .returning();

        created++;
        console.log(`  Created: ${def.promptKey}`);

        // Create dependency mappings
        if (inserted && def.dependencies.length > 0) {
          for (const dep of def.dependencies) {
            await db.insert(promptDependencyMap)
              .values({
                promptId: inserted.id,
                entityType: dep.entityType,
                entityName: dep.entityName,
                endpointPath: dep.endpointPath || null,
                httpMethod: dep.httpMethod || null,
                serviceFunction: dep.serviceFunction,
                direction: dep.direction,
              });
            depCreated++;
          }
        }
      }
    } catch (error: any) {
      console.error(`  Error seeding ${def.promptKey}:`, error.message);
    }
  }

  console.log(`\n=== Seed Complete ===`);
  console.log(`  Created: ${created}`);
  console.log(`  Updated: ${updated}`);
  console.log(`  Skipped: ${skipped}`);
  console.log(`  Dependencies created: ${depCreated}`);
  console.log(`  Total prompts defined: ${allPrompts.length}`);
}

// Run
seedAllPrompts()
  .then(() => {
    console.log('\nDone.');
    process.exit(0);
  })
  .catch((err) => {
    console.error('Seed failed:', err);
    process.exit(1);
  });
